// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBfVm1xw4qRAbLrUOWobl-UNQDQFJziE',
    appId: '1:1007810490380:web:75ed16919846272ed2be29',
    messagingSenderId: '1007810490380',
    projectId: 'attendance-system-a96b0',
    authDomain: 'attendance-system-a96b0.firebaseapp.com',
    storageBucket: 'attendance-system-a96b0.firebasestorage.app',
    measurementId: 'G-G2PR4S4RPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK8NDmLQqXxvT0c-B0WS16gf3GwDUY3RU',
    appId: '1:1007810490380:android:fcc0e9480b434fe4d2be29',
    messagingSenderId: '1007810490380',
    projectId: 'attendance-system-a96b0',
    storageBucket: 'attendance-system-a96b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtpnKk9rtBRnQgvuQVNODm9XDP3SiF3AU',
    appId: '1:1007810490380:ios:a0735959a9250556d2be29',
    messagingSenderId: '1007810490380',
    projectId: 'attendance-system-a96b0',
    storageBucket: 'attendance-system-a96b0.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtpnKk9rtBRnQgvuQVNODm9XDP3SiF3AU',
    appId: '1:1007810490380:ios:a0735959a9250556d2be29',
    messagingSenderId: '1007810490380',
    projectId: 'attendance-system-a96b0',
    storageBucket: 'attendance-system-a96b0.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBfVm1xw4qRAbLrUOWobl-UNQDQFJziE',
    appId: '1:1007810490380:web:cc0e1052c3b64bdfd2be29',
    messagingSenderId: '1007810490380',
    projectId: 'attendance-system-a96b0',
    authDomain: 'attendance-system-a96b0.firebaseapp.com',
    storageBucket: 'attendance-system-a96b0.firebasestorage.app',
    measurementId: 'G-0QQL1BKLL3',
  );
}
